name: Java CI with Maven in Linux
on:
    push:
        branches-ignore:
            - main
jobs:
    build:
        runs-on: ubuntu-24.04
        env:
            workdir: bookstore
        strategy:
            matrix:
                include:
                    - java: 8
                    - java: 11
            fail-fast: false
        name: Build with Java ${{ matrix.java }} on ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Set up JDK ${{ matrix.java }}
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java }}

            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path:
                    ~/.m2
                  key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
                  restore-keys: ${{ runner.os }}-m2-

            - name: Cache Docker images
              uses: actions/cache@v4
              with:
                  path:
                      /var/lib/docker
                  key: ${{ runner.os }}-docker-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-docker-

            - name: Build with Maven
              run: >
                mvn docker:start
                mvn clean verify
                mvn docker:stop
              working-directory: ${{ env.workdir }}

            - name: Generate JUnit Report
              run: mvn surefire-report:report-only site:site -DgenerateReports=false
              working-directory: ${{ env.workdir }}
              if: ${{ always() }}

            - name: Archive JUnit Report
              uses: actions/upload-artifact@v4
              if: ${{ failure() }}
              with:
                name: surefire-report-jdk-${{ matrix.java }}
                path: '**/target/reports'
