name: Java CI with Maven in Linux

on:
    push:
    pull_request:
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-24.04
        env:
            workdir: bookstore
        strategy:
            matrix:
                include:
                    - java: 8
                    - java: 17
                    - java: 11
                      additional-maven-args: >
                        -Pjacoco,mutation-testing
                        sonar:sonar
                        -Dsonar.organization=cmancio00-github
                        -Dsonar.host.url=https://sonarcloud.io
            fail-fast: false
        name: Buil with Java ${{ matrix.java }} on ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK ${{ matrix.java }}
              #setup-java@v4 needs the name of the distribution and the version (8 not 1.8)
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java }}
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: |
                    ~/.m2
                    ~/.sonar/cache
                  key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
                  restore-keys: ${{ runner.os }}-m2-
            - name: Build with Maven
              run: >
                mvn clean verify ${{ matrix.additional-maven-args }}
              working-directory: ${{ env.workdir }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Coveralls
              if: ${{ matrix.java == 11 }}
              uses: coverallsapp/github-action@v2
              env:
                github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Generate JUnit Report
              run: mvn surefire-report:report-only site:site -DgenerateReports=false
              working-directory: ${{ env.workdir }}
              # the if referes to the Generate not the archive
              if: ${{ always() }}
            - name: Archive JUnit Report
              uses: actions/upload-artifact@v4
              if: ${{ failure() }}
              with:
                name: surefire-report-jdk-${{ matrix.java }}
                path: '**/target/reports'
            - name: Archive mutation report
              if: ${{ matrix.java == 11 }}
              uses: actions/upload-artifact@v4
              with:
                name: pit-report-jdk-11
                path: '**/target/pit-reports'
                compression-level: 9
            - name: Upload Pit report to GitHub Pages
              if: ${{ matrix.java == 11 }}
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: '**/target/pit-reports'
