name: Java CI with Maven in Linux

on:
    push:
    pull_request:
jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 8
              #setup-java@v4 needs the name of the distribution and the version (8 not 1.8)
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '8'
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
                  restore-keys: ${{ runner.os }}-m2-
            - name: Build with Maven
              run: mvn -f bookstore/pom.xml clean verify