name: Java CI with Maven in Linux

on:
    push:
    pull_request:
jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@4
            - name: Set up JDK 8
              uses: actions/setup-java@4
              with:
                  java-version: 1.8
            - name: Build with Maven
              run: mvn -f bookstore/pom.xml clean verify