name: Java CI with Maven in Linux

on:
    push:
        branches:
            - '*'
        branches-ignore:
            - 'main'
    pull_request:
jobs:
    build:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                include:
                    - java: 8
                    - java: 11
                      additional-maven-args: "-Pjacoco"
                    - java: 17
            fail-fast: false
        name: Buil with Java ${{ matrix.java }} on ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK ${{ matrix.java }}
              #setup-java@v4 needs the name of the distribution and the version (8 not 1.8)
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java }}
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
                  restore-keys: ${{ runner.os }}-m2-
            - name: Build with Maven
              run: mvn -f bookstore/pom.xml clean verify ${{ matrix.additional-maven-args }}
            - name: Generate JUnit Report
              run: mvn -f bookstore/pom.xml surefire-report:report-only site:site -DgenerateReports=false
              # the if referes to the Generate not the archive
              if: ${{ always() }}
            - name: Archive JUnit Report
              uses: actions/upload-artifact@v4
              if: ${{ failure() }}
              with:
                name: surefire-report-jdk-${{ matrix.java }}
                path: '**/target/reports'