name: Java CI with Maven in Linux

on:
    push:
    pull_request:
jobs:
    build:
        runs-on: ${{ matrix.os}}
        strategy:
            matrix:
                os: [ubuntu-24.04, windows-2022]
                java: [8, 11, 17]
            fail-fast: false
        name: Buil with Java ${{ matrix.java }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK ${{ matrix.java }}
              #setup-java@v4 needs the name of the distribution and the version (8 not 1.8)
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: ${{ matrix.java }}
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
                  restore-keys: ${{ runner.os }}-m2-
            - name: Build with Maven
              run: mvn -f bookstore/pom.xml clean verify
            - name: Generate JUnit Report
              run: mvn surefire-report:report-only site:site -DgenerateReports=false
              if: ${{ failure() }}
            - name: Archive JUnit Report
              uses: actions/upload-artifact@v4
              with:
                name: surefire-report-jdk-${{ matrix.java }}
                path: '**/target/reports'