name: Code Quality Checks

on:
  push:
  pull_request:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      workdir: bookstore
    strategy:
      matrix:
        include:
          - java: 17

      fail-fast: false
    name: Build with Java ${{ matrix.java }} on ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
              #setup-java@v4 needs the name of the distribution and the version (8 not 1.8)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path:
            ~/.m2
          key: ${{ runner.os }}-m2-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml', '**/*.yml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Cache Docker images
        uses: actions/cache@v4
        with:
            path:
                /var/lib/docker
            key: ${{ runner.os }}-docker-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-docker-

      - name: Cache Sonar Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Pit history
        uses: actions/cache@v4
        with:
          path: ${{ env.workdir }}
          key: ${{ runner.os }}-pit
          restore-keys: ${{ runner.os }}-pit

      - name: Build with Maven
        run: >
            mvn docker:start
            mvn clean verify -Pjacoco,mutation-testing
            mvn docker:stop
        working-directory: ${{ env.workdir }}

      - name: Generate JUnit Report
        run: mvn surefire-report:report-only site:site -DgenerateReports=false
        working-directory: ${{ env.workdir }}
        if: ${{ always() }}
      - name: Archive JUnit Report
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: surefire-report-jdk-${{ matrix.java }}
          path: '**/target/reports'

      - name: Archive mutation report
        uses: actions/upload-artifact@v4
        with:
          name: pit-report-jdk-17
          path: '**/target/pit-reports'
          compression-level: 9
      - name: Upload Pit report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: '**/target/pit-reports'

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        env:
         github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarCloud
        run: mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        working-directory: ${{ env.workdir }}