name: Java CI with Maven on Windows

on:
    pull_request:
jobs:
    build:
        runs-on: windows-2022
        name: Buil with Java 11 on windows-2022
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 11
              #setup-java@v4 needs the name of the distribution and the version (8 not 1.8)
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '11'
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
                  restore-keys: ${{ runner.os }}-m2-
            - name: Build with Maven
              run: mvn -f bookstore/pom.xml clean verify
            - name: Generate JUnit Report
              run: mvn -f bookstore/pom.xml surefire-report:report-only site:site -DgenerateReports=false
              # the if referes to the Generate not the archive
              if: ${{ always() }}
            - name: Archive JUnit Report
              uses: actions/upload-artifact@v4
              if: ${{ failure() }}
              with:
                name: surefire-report-jdk-${{ matrix.java }}
                path: '**/target/reports'